using System.IO;
using System.Linq;
using System.Text;
using UnityEditor;
using UnityEngine;

namespace Feather.Editor
{
    public static class LinkXmlGenerator
    {
        private const string OutputPath = "Assets/Feather/link.xml";

        public static void Generate()
        {
            var assemblies = UnityApiSurface.GetAssemblies()
                .Select(a => a.GetName().Name)
                .Distinct()
                .OrderBy(n => n)
                .ToList();

            var sb = new StringBuilder();
            sb.AppendLine("<!-- Auto-generated by Feather (Generate / Update JS Project) -->");
            sb.AppendLine("<!-- Preserve types exposed to Jint JavaScript interop -->");
            sb.AppendLine("<linker>");
            foreach (var name in assemblies)
            {
                sb.AppendLine($"  <assembly fullname=\"{name}\" preserve=\"all\" />");
            }
            // Feather runtime + plugins
            sb.AppendLine("  <assembly fullname=\"Assembly-CSharp\" preserve=\"all\" />");
            sb.AppendLine("</linker>");

            File.WriteAllText(OutputPath, sb.ToString());
            AssetDatabase.Refresh();
            Debug.Log($"[Feather] Wrote {OutputPath} ({assemblies.Count} assemblies preserved)");
        }
    }
}
